DELIMITER $$
  CREATE EVENT delete_post
  ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY
  ON COMPLETION PRESERVE
  DO
    BEGIN
      DELETE Post WHERE duration < DATE_SUB(NOW(), INTERVAL 1 MONTH);
    END;
$$;